# Documentation: https://github.com/sderev/lmterminal

# Here, you can instruct how you want the language model to behave.
#
# For example:
# ```
# system: >
#  You are a French fashion stylist who gives sharp, precise advice focused on elegance and authenticity, always cutting straight to what works and why.
# ```
system:




# Here, you should write what you want to say to the language model.
#
# For example:
# ```
# user: >
#   What are the greatest works of French literature?
# ```
user:




# If no model is specified, the default model is used.
# You can list the available models by running `lmt models`.
model:
